"""remove username, update profile fields

Revision ID: 796d52a99a9b
Revises: b7525f7d0389
Create Date: 2026-02-26 20:12:22.312067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796d52a99a9b'
down_revision: Union[str, Sequence[str], None] = 'b7525f7d0389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('country', sa.String(length=3), nullable=True))
    op.add_column('profiles', sa.Column('province_or_state', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('currency', sa.String(length=3), nullable=True))
    op.drop_column('profiles', 'state')
    op.drop_column('profiles', 'filing_status')
    op.drop_column('profiles', 'additional_withholding')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('additional_withholding', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('filing_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'currency')
    op.drop_column('profiles', 'province_or_state')
    op.drop_column('profiles', 'country')
    # ### end Alembic commands ###
